### ISSUE TITLE
Я обнаружила ошибку

### ISSUE THREAD

**Issue by Allekara** [1maker/VR_central_repository#3]
В 3.2

**Comment by 1maker** [comment]
Какая строка в этом файле?

**Comment by Allekara** [comment]
На 15 строке)

**Comment by dryuher** [comment]
это я сломал (´･ᴗ･ ` )

**Comment by 1maker** [comment]
Спасибо @Allekara за содействие! Ошибка устранена.

**Comment by 1maker** [comment]
@dryuher Больше так не делай! :)

**Comment by dryuher** [comment]
@1maker Хорошо

**Comment by Kenndly** [comment]
А меня тоже удалите?

**Comment by 1maker** [comment]
Ребята, давайте жить дружно!
